import React, { useState, useEffect } from 'react'
import { 
  X, 
  Loader2, 
  FileText, 
  Copy, 
  Check, 
  Sparkles, 
  Clock, 
  DollarSign, 
  ShieldAlert
} from 'lucide-react'

const renderMarkdown = (text) => {
  if (!text) return null
  
  const lines = text.split('\n')
  return lines.map((line, idx) => {
    const trimmed = line.trim()
    
    // Parse inline bolding: replace **text** with <strong>text</strong>
    const parseInline = (str) => {
      const parts = str.split('**')
      return parts.map((part, i) => {
        if (i % 2 === 1) {
          return <strong key={i} style={{ color: 'var(--color-primary)', fontWeight: 700 }}>{part}</strong>
        }
        return part
      })
    }

    // Header 1
    if (trimmed.startsWith('# ')) {
      return (
        <h1 key={idx} style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginTop: '20px', marginBottom: '10px', borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>
          {parseInline(trimmed.substring(2))}
        </h1>
      )
    }
    
    // Header 2
    if (trimmed.startsWith('## ')) {
      return (
        <h2 key={idx} style={{ fontSize: '1.25rem', color: 'var(--color-primary)', marginTop: '16px', marginBottom: '8px' }}>
          {parseInline(trimmed.substring(3))}
        </h2>
      )
    }
    
    // Header 3
    if (trimmed.startsWith('### ')) {
      return (
        <h3 key={idx} style={{ fontSize: '1.1rem', color: 'var(--text-primary)', marginTop: '12px', marginBottom: '6px' }}>
          {parseInline(trimmed.substring(4))}
        </h3>
      )
    }
    
    // Blockquote
    if (trimmed.startsWith('> ')) {
      return (
        <blockquote key={idx} style={{ 
          borderLeft: '4px solid var(--color-primary)', 
          background: 'rgba(6,182,212,0.05)', 
          padding: '10px 14px', 
          borderRadius: '6px',
          margin: '10px 0', 
          color: 'var(--text-secondary)',
          fontStyle: 'italic',
          fontSize: '0.9rem'
        }}>
          {parseInline(trimmed.substring(2))}
        </blockquote>
      )
    }
    
    // Bullet Points
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      return (
        <li key={idx} style={{ marginLeft: '20px', marginBottom: '4px', color: 'var(--text-secondary)', fontSize: '0.9rem', listStyleType: 'disc' }}>
          {parseInline(trimmed.substring(2))}
        </li>
      )
    }

    // Numbered Lists
    const numMatch = trimmed.match(/^(\d+)\.\s(.*)/)
    if (numMatch) {
      return (
        <div key={idx} style={{ marginLeft: '16px', marginBottom: '4px', color: 'var(--text-secondary)', fontSize: '0.9rem', display: 'flex', gap: '8px' }}>
          <span style={{ color: 'var(--color-primary)', fontWeight: 600 }}>{numMatch[1]}.</span>
          <span>{parseInline(numMatch[2])}</span>
        </div>
      )
    }
    
    // Empty line
    if (trimmed === '') {
      return <div key={idx} style={{ height: '8px' }} />
    }
    
    // Standard paragraph
    return (
      <p key={idx} style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.5, marginBottom: '8px' }}>
        {parseInline(line)}
      </p>
    )
  })
}

const UI_TEXT = {
  en: {
    modalTitle: "Project Collaboration Proposal",
    modalSubtitle: "Agent 7 (Proposal Generator) is compiling a deployment plan bridging academic research with Syrian post-war community reconstruction.",
    step1: "Extracting project constraints & requirements...",
    step2: "Assembling interdisciplinary researcher team...",
    step3: "Calculating budget allocation & timelines...",
    step4: "Generating final proposal document...",
    copyBtn: "Copy Proposal",
    copiedBtn: "Copied!",
    closeBtn: "Close Document",
    agentNotice: "This proposal was generated by Agent 7 based on matching researcher directories to ensure academic theories (e.g. machine learning structures, concrete composition, seismic models) are properly deployed to produce a useful, tangible output for community benefit.",
    loadingText: "Agent Processing...",
    failedGenerate: "Failed to generate proposal",
    genericGenerateError: "An error occurred during proposal generation.",
    failedCompileTitle: "Failed to compile proposal"
  },
  ar: {
    modalTitle: "مقترح التعاون المشترك للمشروع",
    modalSubtitle: "يقوم الوكيل 7 (معد المقترحات) بصياغة خطة عمل لسد الفجوة بين الأبحاث الأكاديمية وإعادة إعمار المجتمعات المتضررة في سوريا.",
    step1: "استخراج محددات ومتطلبات المشروع...",
    step2: "تجميع فريق الباحثين متعدد التخصصات الملاءم...",
    step3: "حساب الميزانيات التقديرية والجداول الزمنية...",
    step4: "صياغة مستند المقترح النهائي المشترك...",
    copyBtn: "نسخ المقترح",
    copiedBtn: "تم النسخ!",
    closeBtn: "إغلاق المستند",
    agentNotice: "تم صياغة هذا المقترح بواسطة الوكيل 7 بناءً على مطابقة الخبراء المتاحين لضمان انتقال النظريات الأكاديمية (مثل هندسة البرمجيات، نماذج التعلم الآلي، هندسة الزلازل) إلى مخرجات حقيقية تخدم الإنسانية.",
    loadingText: "جاري المعالجة...",
    failedGenerate: "فشل إنشاء المقترح",
    genericGenerateError: "حدث خطأ أثناء إنشاء المقترح.",
    failedCompileTitle: "فشل صياغة المقترح"
  }
}

function ProposalModal({ projectId, onClose, lang }) {
  const activeLang = lang || 'en'
  const t = UI_TEXT[activeLang]

  const [loading, setLoading] = useState(true)
  const [activeStep, setActiveStep] = useState(1) // 1 to 4
  const [proposal, setProposal] = useState('')
  const [copied, setCopied] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!projectId) return

    setLoading(true)
    setError('')
    setActiveStep(1)

    const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

    // Start API request
    const fetchPromise = fetch(`/api/projects/${projectId}/proposal`)
      .then(async (res) => {
        const data = await res.json()
        if (!res.ok) {
          throw new Error(data.detail || t.failedGenerate)
        }
        return data.proposal
      })

    const runSimulation = async () => {
      try {
        await delay(1000)
        setActiveStep(2)
        await delay(1000)
        setActiveStep(3)
        await delay(1000)
        setActiveStep(4)
        await delay(800)

        const text = await fetchPromise
        setProposal(text)
        setLoading(false)
      } catch (err) {
        console.error(err)
        setError(err.message || t.genericGenerateError)
        setLoading(false)
      }
    }

    runSimulation()
  }, [projectId])

  const handleCopy = () => {
    if (!proposal) return
    navigator.clipboard.writeText(proposal)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // Prevent background clicks from closing modal accidentally if clicked on main container
  const handleContainerClick = (e) => {
    e.stopPropagation()
  }

  return (
    <div 
      onClick={onClose}
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(3, 7, 18, 0.85)',
        backdropFilter: 'blur(8px)',
        zIndex: 1000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
        direction: activeLang === 'ar' ? 'rtl' : 'ltr'
      }}
    >
      <div 
        onClick={handleContainerClick}
        className="glass-panel" 
        style={{
          width: '100%',
          maxWidth: '850px',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          border: '1px solid rgba(6, 182, 212, 0.25)',
          boxShadow: '0 20px 40px rgba(0, 0, 0, 0.5), var(--shadow-glow)',
          animation: 'scale-up 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)'
        }}
      >
        {/* Modal Header */}
        <div style={{
          padding: '24px 30px',
          borderBottom: '1px solid var(--border-color)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexShrink: 0
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              background: 'var(--grad-primary)',
              width: '40px',
              height: '40px',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}>
              <FileText size={20} style={{ color: '#fff' }} />
            </div>
            <div>
              <h3 style={{ fontSize: '1.35rem', fontWeight: 800, margin: 0 }}>
                {t.modalTitle}
              </h3>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', marginTop: '2px', display: 'none' }}>
                {t.modalSubtitle}
              </p>
            </div>
          </div>
          <button 
            type="button"
            onClick={onClose}
            style={{
              background: 'none',
              border: 'none',
              color: 'var(--text-muted)',
              cursor: 'pointer',
              padding: '6px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: 'rgba(255, 255, 255, 0.02)',
              border: '1px solid var(--border-color)',
              transition: 'all 0.2s'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.color = 'var(--text-primary)';
              e.currentTarget.style.borderColor = 'rgba(255,255,255,0.2)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.color = 'var(--text-muted)';
              e.currentTarget.style.borderColor = 'var(--border-color)';
            }}
          >
            <X size={16} />
          </button>
        </div>

        {/* Modal Body */}
        <div style={{
          padding: '30px',
          overflowY: 'auto',
          flexGrow: 1,
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: 'rgba(11, 15, 25, 0.4)'
        }}>
          {loading && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flexGrow: 1, padding: '40px 0' }}>
              <Loader2 size={40} className="animate-spin" style={{ color: 'var(--color-primary)', marginBottom: '30px' }} />
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', width: '100%', maxWidth: '380px' }}>
                <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase', textAlign: 'center', marginBottom: '6px', letterSpacing: '0.05em' }}>
                  {t.loadingText}
                </span>

                {/* Step 1 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', fontSize: '0.85rem' }}>
                  <div style={{
                    width: '18px',
                    height: '18px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: activeStep > 1 ? 'var(--color-accent)' : activeStep === 1 ? 'rgba(6, 182, 212, 0.15)' : 'rgba(255, 255, 255, 0.02)',
                    border: '1px solid ' + (activeStep > 1 ? 'var(--color-accent)' : activeStep === 1 ? 'var(--color-primary)' : 'var(--border-color)'),
                    color: activeStep > 1 ? '#fff' : 'inherit'
                  }}>
                    {activeStep > 1 ? <Check size={10} /> : "1"}
                  </div>
                  <span style={{ color: activeStep === 1 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: activeStep === 1 ? '600' : 'normal' }}>
                    {t.step1}
                  </span>
                </div>

                {/* Step 2 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', fontSize: '0.85rem' }}>
                  <div style={{
                    width: '18px',
                    height: '18px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: activeStep > 2 ? 'var(--color-accent)' : activeStep === 2 ? 'rgba(139, 92, 246, 0.15)' : 'rgba(255, 255, 255, 0.02)',
                    border: '1px solid ' + (activeStep > 2 ? 'var(--color-accent)' : activeStep === 2 ? 'var(--color-secondary)' : 'var(--border-color)'),
                    color: activeStep > 2 ? '#fff' : 'inherit'
                  }}>
                    {activeStep > 2 ? <Check size={10} /> : "2"}
                  </div>
                  <span style={{ color: activeStep === 2 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: activeStep === 2 ? '600' : 'normal' }}>
                    {t.step2}
                  </span>
                </div>

                {/* Step 3 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', fontSize: '0.85rem' }}>
                  <div style={{
                    width: '18px',
                    height: '18px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: activeStep > 3 ? 'var(--color-accent)' : activeStep === 3 ? 'rgba(16, 185, 129, 0.15)' : 'rgba(255, 255, 255, 0.02)',
                    border: '1px solid ' + (activeStep > 3 ? 'var(--color-accent)' : activeStep === 3 ? 'var(--color-accent)' : 'var(--border-color)'),
                    color: activeStep > 3 ? '#fff' : 'inherit'
                  }}>
                    {activeStep > 3 ? <Check size={10} /> : "3"}
                  </div>
                  <span style={{ color: activeStep === 3 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: activeStep === 3 ? '600' : 'normal' }}>
                    {t.step3}
                  </span>
                </div>

                {/* Step 4 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', fontSize: '0.85rem' }}>
                  <div style={{
                    width: '18px',
                    height: '18px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: activeStep > 4 ? 'var(--color-accent)' : activeStep === 4 ? 'rgba(6, 182, 212, 0.15)' : 'rgba(255, 255, 255, 0.02)',
                    border: '1px solid ' + (activeStep > 4 ? 'var(--color-accent)' : activeStep === 4 ? 'var(--color-primary)' : 'var(--border-color)'),
                    color: activeStep > 4 ? '#fff' : 'inherit'
                  }}>
                    {activeStep > 4 ? <Check size={10} /> : "4"}
                  </div>
                  <span style={{ color: activeStep === 4 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: activeStep === 4 ? '600' : 'normal' }}>
                    {t.step4}
                  </span>
                </div>
              </div>
            </div>
          )}

          {error && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flexGrow: 1, gap: '14px', color: 'var(--color-error)' }}>
              <ShieldAlert size={48} />
              <h4 style={{ fontSize: '1.25rem', fontWeight: 700 }}>{t.failedCompileTitle}</h4>
              <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', textAlign: 'center', maxWidth: '400px' }}>{error}</p>
            </div>
          )}

          {!loading && !error && proposal && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
              
              {/* Agent Alert Info */}
              <div style={{
                padding: '16px 20px',
                borderRadius: '12px',
                backgroundColor: 'rgba(6, 182, 212, 0.04)',
                border: '1px solid rgba(6, 182, 212, 0.15)',
                fontSize: '0.85rem',
                lineHeight: 1.5,
                color: 'var(--text-secondary)',
                display: 'flex',
                gap: '12px',
                alignItems: 'flex-start'
              }}>
                <Sparkles size={18} style={{ color: 'var(--color-primary)', flexShrink: 0, marginTop: '2px' }} />
                <span>{t.agentNotice}</span>
              </div>

              {/* Proposal Content Render */}
              <div style={{
                backgroundColor: 'rgba(0, 0, 0, 0.2)',
                border: '1px solid var(--border-color)',
                borderRadius: '14px',
                padding: '24px 30px',
                boxShadow: 'inset 0 2px 8px rgba(0,0,0,0.2)'
              }}>
                {renderMarkdown(proposal)}
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        {!loading && !error && proposal && (
          <div style={{
            padding: '20px 30px',
            borderTop: '1px solid var(--border-color)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexShrink: 0
          }}>
            <button
              type="button"
              onClick={handleCopy}
              className="btn btn-secondary"
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '10px 16px',
                fontSize: '0.85rem'
              }}
            >
              {copied ? (
                <>
                  <Check size={14} style={{ color: 'var(--color-accent)' }} />
                  <span style={{ color: 'var(--color-accent)' }}>{t.copiedBtn}</span>
                </>
              ) : (
                <>
                  <Copy size={14} />
                  <span>{t.copyBtn}</span>
                </>
              )}
            </button>

            <button
              type="button"
              onClick={onClose}
              className="btn btn-primary"
              style={{
                padding: '10px 18px',
                fontSize: '0.85rem'
              }}
            >
              {t.closeBtn}
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

export default ProposalModal
